name: HelpCommand
version: '2.7.6-PublicRelease'
main: net.greenwoodmc.helpcommand.HelpCommand
api-version: 1.18
authors: [ VoidemLIVE ]
description: Simple custom help command
website: helpcommand.greenwoodmc.net

softdepend: [PlaceholderAPI]

commands:
  help:
    description: Help command
  hc:
    description: Help Command plugin options
    permission: hc.admin
    permission-message: No permission